# Python Libraries - Assignment 1

## NumPy Exercises

In [3]:
# Import NumPy library
import numpy as np

### Array Creation

In [5]:
# 1. Create a numpy array of size 10, filled with zeros
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# 2. Create a numpy array with values ranging from 10 to 49 and set its datatype to float
array = np.arange(10, 50, dtype=float)
array

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

In [16]:
# 3. Create a numpy matrix of 2*2 integers, filled with ones
ones_integer = np.ones((2, 2), dtype=int)
ones_integer

array([[1, 1],
       [1, 1]])

In [17]:
# 4. Create a numpy matrix of 3*2 float numbers, filled with ones
ones_float = np.ones((3, 2))
ones_float

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
# 5. Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

ones_like_X = np.ones_like(X)
ones_like_X

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
# 6. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros
X = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0]])

zeros_like_X = np.zeros_like(X)
zeros_like_X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
# 7. Create a numpy matrix of 4*4 integers, filled with fives
fives = np.full((4, 4), fill_value=5, dtype=int)
fives

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [47]:
# 8. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens
X = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

sevens_like_X = np.full_like(X, fill_value=7)
sevens_like_X

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [53]:
# 9. Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# 10. Create a numpy array, filled with 3 random integer values between 1 and 10
random_array = np.random.randint(1, 10, size=3, dtype=int)
random_array

array([7, 1, 3])

In [64]:
# 11. Create a 3*3*3 numpy matrix, filled with random float values
random_floats = np.random.rand(3, 3, 3)
random_floats

array([[[0.91742879, 0.22146888, 0.34532621],
        [0.09425404, 0.4366447 , 0.52194893],
        [0.38543236, 0.64701532, 0.93601754]],

       [[0.37740584, 0.27020105, 0.49122601],
        [0.70862462, 0.80648804, 0.81827038],
        [0.6839267 , 0.34266457, 0.96493305]],

       [[0.41954646, 0.1982823 , 0.42568778],
        [0.79305366, 0.74314597, 0.09490929],
        [0.6309204 , 0.90034132, 0.472839  ]]])

In [66]:
# 12. Create a numpy array with numbers from 1 to 10
numbers = np.arange(1, 11)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# 13. Create a numpy array with the odd numbers between 1 to 10
odds = np.arange(1, 10, 2)
odds

array([1, 3, 5, 7, 9])

In [71]:
# 14. Create a numpy array with numbers from 1 to 10, in descending order
numbers_desc = np.arange(1, 11)[::-1]
numbers_desc

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [73]:
# 15. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Array Indexing

In [77]:
# 1. Given the X numpy array, show its first element
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [78]:
# 2. Given the X numpy array, show its last element
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [86]:
# 3. Given the X numpy array, show its first three elements
X = np.array(['A','B','C','D','E'])
print(X[0:3])

['A' 'B' 'C']


In [90]:
# 4. Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])
print(X[1:-1])

['B' 'C' 'D']


In [94]:
# 5. Given the X numpy array, show the elements in reverse position
X = np.array(['A','B','C','D','E'])
print(X[::-1])

['E' 'D' 'C' 'B' 'A']


In [96]:
# 6. Given the X numpy array, show the elements in an odd position
X = np.array(['A','B','C','D','E'])
print(X[0::2])

['A' 'C' 'E']


In [98]:
# 7. Given the X numpy matrix, show the first row’s elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[0])

[1 2 3 4]


In [99]:
# 8. Given the X numpy matrix, show the last row elements.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[-1])

[13 14 15 16]


In [106]:
# 9. Given the X numpy matrix, show the first element on first row

X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[0,0]

1

In [107]:
# 10. Given the X numpy matrix, show the last element on last row

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1]

16

In [109]:
# 11. Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[0:2,0:2])

[[1 2]
 [5 6]]


In [114]:
# 12. Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[-2:, -2:])

[[11 12]
 [15 16]]


### Array Manipulation

In [117]:
# 1. Convert the given integer numpy array to float
X = np.array([-5, -3, 0, 10, 40])
X_float = X.astype(float)
X_float

array([-5., -3.,  0., 10., 40.])

In [120]:
# 2.	Reverse the given numpy array (first element becomes last) through indexing
X = np.array([-5, -3, 0, 10, 40])
X = X[::-1]
print(X)

[40 10  0 -3 -5]


In [122]:
# 3.	Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [123]:
# 4. Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[3] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [124]:
# 5.	Given the X numpy matrix, add 5 to every element

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X = X + 5
X

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])